#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/config.mysql 
  dbc_go _APP_NAME_-mysql $@
fi

