#!/bin/sh -e

APP_NAME="_APP_NAME_"
APP_SAFE_NAME="_APP_SAFE_NAME_"

# Source debconf library.
. /usr/share/debconf/confmodule

db_input high ${APP_NAME}/mysql/autoinstall || true
db_go

db_get ${APP_NAME}/mysql/autoinstall
if [ "$RET" = "false" ]; then
  exit 0
fi

db_input high ${APP_NAME}/mysql/db_host || true
db_input high ${APP_NAME}/mysql/db_port || true
db_input high ${APP_NAME}/mysql/admin_username || true
db_input high ${APP_NAME}/mysql/admin_password || true

db_go

db_get ${APP_NAME}/mysql/db_host
dbc_host="$RET"
db_get ${APP_NAME}/mysql/db_port
dbc_port="$RET"
db_get ${APP_NAME}/mysql/admin_username
dbc_admin_username="$RET"
db_get ${APP_NAME}/mysql/admin_password
dbc_admin_password="$RET"

tmpfile=$(mktemp)
cat > $tmpfile <<CONFIG
[client]
password="${dbc_admin_password}"
user="${dbc_admin_user}"
host="${dbc_host}"
port="${dbc_port}"
CONFIG

set +e
test_connection=$(mysql --defaults-file="$tmpfile" -e "select count(*) from mysql.user;")
test_status=$?

rm -f "$tmpfile"

if [ $test_status -eq 0 ]; then
  echo "MySQL connection OK"
else
  echo "$test_connection"
  db_input high ${APP_NAME}/mysql/connection_failed || true
  db_go
  exit 1
fi
set -e

db_input medium ${APP_NAME}/mysql/db_username || true
db_input medium ${APP_NAME}/mysql/db_password || true
db_go

db_get ${APP_NAME}/mysql/db_password
if [ "$RET" = "" ]; then
  dbc_password=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32;echo;)
  db_set ${APP_NAME}/mysql/db_password "$dbc_password"
fi

db_input medium ${APP_NAME}/mysql/db_name || true
db_go

