#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

APP_NAME="_APP_NAME_"
TEMPLATE="/usr/share/${APP_NAME}-mysql/templates/database.template"
OUTPUT="/etc/${APP_NAME}/conf.d/database"

# source debconf library
. /usr/share/debconf/confmodule

mysql_execute() {
  local command="$1"
  mysql -u"${dbc_admin_username}" -p"${dbc_admin_password}" -h"${dbc_host}" -P"${dbc_port}" -e "$command"
}

case "$1" in

  configure)

    db_get ${APP_NAME}/mysql/autoinstall

    if [ "$RET" = "false" ]; then
      exit 0
    else
      db_get ${APP_NAME}/mysql/admin_username
      dbc_admin_username="$RET"
      db_get ${APP_NAME}/mysql/admin_password
      dbc_admin_password="$RET"
      db_get ${APP_NAME}/mysql/db_host
      dbc_host="$RET"
      db_get ${APP_NAME}/mysql/db_port
      dbc_port="$RET"
      db_get ${APP_NAME}/mysql/db_username
      dbc_username="$RET"
      db_get ${APP_NAME}/mysql/db_password
      dbc_password="$RET"
      db_get ${APP_NAME}/mysql/db_name
      dbc_name="$RET"

      if mysql_execute "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = '${dbc_username}')" &>/dev/null ; then
	echo "user ${dbc_username} already exists."
      else
	mysql_execute "CREATE USER '${dbc_username}'@'${dbc_host}' IDENTIFIED BY '${dbc_password}';"
      fi

      mysql_execute "CREATE DATABASE IF NOT EXISTS '${dbc_name}' CHARACTER SET utf8;"

      mysql_execute "GRANT ALL PRIVILEGES ON ${dbc_name}.* TO '${dbc_username}'@'${dbc_host}'; FLUSH PRIVILEGES;";
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

