#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

APP_NAME="_APP_NAME_"
TEMPLATE="/usr/share/${APP_NAME}-mysql/templates/database.template"
OUTPUT="/etc/${APP_NAME}/conf.d/database"

# source debconf library
. /usr/share/debconf/confmodule

mysql_execute() {
  local defaults_file="$1"
  local command="$2"

  mysql --defaults-file="$defaults_file" -e "$command"
}

generate_database_template() {
  local tmpfile=$(mktemp)
  cp "${TEMPLATE}" "${tmpfile}"
  sed -i "s/_DBC_DBTYPE_/mysql/g" ${tmpfile}
  sed -i "s/_DBC_DBUSER_/${dbc_username}/g" ${tmpfile}
  sed -i "s/_DBC_DBPASS_/${dbc_password}/g" ${tmpfile}
  sed -i "s/_DBC_DBSERVER_/${dbc_host}/g" ${tmpfile}
  sed -i "s/_DBC_DBPORT_/${dbc_port}/g" ${tmpfile}
  sed -i "s/_DBC_DBNAME_/${dbc_name}/g" ${tmpfile}
  echo "Generating ${OUTPUT}..."
  mv "${tmpfile}" "${OUTPUT}"
}

case "$1" in

  configure)

    db_get ${APP_NAME}/mysql/autoinstall

    if [ "$RET" = "false" ]; then
      exit 0
    else
      db_get ${APP_NAME}/mysql/admin_username
      dbc_admin_username="$RET"
      db_get ${APP_NAME}/mysql/admin_password
      dbc_admin_password="$RET"
      db_get ${APP_NAME}/mysql/db_host
      dbc_host="$RET"
      db_get ${APP_NAME}/mysql/db_port
      dbc_port="$RET"
      db_get ${APP_NAME}/mysql/db_username
      dbc_username="$RET"
      db_get ${APP_NAME}/mysql/db_password
      dbc_password="$RET"
      db_get ${APP_NAME}/mysql/db_name
      dbc_name="$RET"

      tmpfile=$(mktemp)
      cat > $tmpfile <<CONFIG
[client]
password="${dbc_admin_password}"
user="${dbc_admin_user}"
host="${dbc_host}"
port="${dbc_port}"
CONFIG

      mysql_execute "$tmpfile" "GRANT USAGE ON *.* TO '${dbc_username}'@'${dbc_host}' IDENTIFIED BY '${dbc_password}';"

      mysql_execute "$tmpfile" "CREATE DATABASE IF NOT EXISTS \`${dbc_name}\` CHARACTER SET utf8;"

      mysql_execute "$tmpfile" "GRANT ALL PRIVILEGES ON \`${dbc_name}\`.* TO '${dbc_username}'@'${dbc_host}'; FLUSH PRIVILEGES;";

      rm -f "$tmpfile"

      generate_database_template
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

